sudo: false
language: node.js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
install:
  - npm run setup
before_script:
  - npm test
script:
  - npm run build
deploy: &heroku
  provider: heroku
  app: game-2048
  on: master
  run: "npm run server"
  api_key: eipXqqgoRxfaB0WtyiklaUqeoQyhXVP3YLupdDnFzXne4eCaXG2xBAv55KkVZj5OMcNklfTYPHPrlhcAn4lQmy/Ul9LNCQZuUGzHHYtXCjmvXDoEK9Xnma9biWuiarO5gQ5T07Om2akTNiTul3UIqexzjMq8iOTkRZGrFd64fOmjgAje9B6hK1bWVRbsM/lpFWAWz7p29sA5y4hnscEEi1BlJSVT8EiWYmogRFlBU0tmF4PZuV7GY3Z/UkRKhQLvysFnaQ1M+cbtoMcxsah9OhVDiv2fLuDj6YS3VkEflgs2ab5OLQfqS1sasGp/66oHwyVkMN/eEpRSdiK4oE3YXMkP7ip4H8aeKw0tG03dTegKgt+Cs1tJwCPVuHJN0XLzQBcVCF3gL08ntHvqvkIkLCcTVx6sy7XCAjNH713zqCCXrBY2B5arKcUhxc0soRSqhSFmpK2C2WxSpI7UHCee4WFt7667Dp8nHp7i4A1F1qV6Bn7OF1e0LD2Nsf+shI+WqF8HnDL9w6ixHC4NaDrEIf3KGiOyJojLr22ujQg3mJTJCGv07Vdr1uTkiowYcg09e/ZX1SNuAwWWeDhF/fxMMG3ZH5vU08+A/q+IngB5npwmMRAxozwlsRyNHIZgZxbhhrXFPMGyQTLhTmDly8Jvo9KYaJVtKXUEY7U3p/pit8k=