sudo: false
language: node.js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- npm run setup
before_script:
- npm test
script:
- npm run build
deploy:
  provider: heroku
  app: sheltered-sea-41755
  on: master
  run: npm run server
  api_key:
    secure: YfeVwvf+2xhoDlHO3sL/vQP5sY74mVBC5ryQ6rHfTfdaderE5iHxUtFGLGjklK6E1zP0GfpZcUuAQGXKxxQGrZswyTE328h8HNbNGwwJ0rr7lcr7EHWvLJjbwVUn4+vrvEJSW9vL4GacTmJQ6/fiwTJraYziZfm4JV65T8uXwVzSHKnJh3fxjtP2wmF1cFvfIT2+gbLTMqZIrImmHBx0Nk4SelDLKOOan4/Y9J/KWvXTJ6XZuQPU/O+p3lPZpT8UGRXAio0HSYPZ3YhrW6BW7nwJ3QWGd1L39DoL4uNGMT+FUxxj1StYZTiRSDVzoIBcEOhp6Qw6aFgLk5VREPN+WhjvZ1STY/vud+ALANQzjI8r38NN38bWPpsgwcZd3bZc9bnWLdDJReE24MNxDSAVgQxOVWJ9LfTQYJ8gSHx6WAtcVNG7X75AZ25Pm3rOgCjEZqsNk+SD1RZ8IP1IM0QGMhd0a8Edv3+BDiSoT8XV/XQi70moJ5/OG01dUDlISfEHGXNKWH4TUBjdBd+yezvRlTZ7yyaZf6+9LDHU1RZUIyRkTwU5/+ZV+a8fFa+vlTMWn904zOl5EGR1bUWep1TocNX2Tofs060DhsGzSjy9zAZQJc7CorRRa93MeXXqwqqY8ll9cZ+TnetbYgB8fS36QWQpp7AD7u+UmULUXnwxR7g=
